### ISSUE TITLE
새가족국 소속 인원 등록

### ISSUE THREAD

**Issue by gyummy** [dkeplusi-database/nurture-management-system#65]
새가족국 소속 인원을 시스템에 등록한다.
새가족국 국장 및 순장들 중 일부는 현재 시스템에 누락되어있다.
이를 확인하고, 2020년도 조직 구성 확정 이후 반영하도록 한다.

**Comment by gyummy** [comment]
새가족국 간사에게 부탁할 예정

**Comment by HWANGJUNYOUNGG** [comment]
제가 이해하기로는 2020년 조직도에서 새가족부에 있는 순장들을 시스템 관리자(사용자)로 등록하는 걸로 이해했는데요.
데이버베이스를 보니 ORGANIZATION Table에서 새가족부 관련한 것은 없는데, 상관이 없는 건가요??
그냥 새가족국 간사님이 순장들의 계정만 추가 하면 되는 건가요?

**Comment by gyummy** [comment]
@HWANGJUNYOUNGG 그냥 2019년도 새가족국 소속 인원들의 청년 정보를 입력해달라는 요청에서 시작된 이슈라 ㅎㅎ 이미 국장님이 처리하셨다고 하니 이 이슈는 닫도록 합니다.
