### ISSUE TITLE
2020년 조직 구성안 적용

### ISSUE THREAD

**Issue by gyummy** [dkeplusi-database/nurture-management-system#66]
2020년 조직 구성안 확정 후, 해당 구성안을 시스템에 실제 적용

**Comment by gyummy** [comment]
12월 14일까지 양육부 조직도안 받기로 결정

**Comment by gyummy** [comment]
2020년도 순배정 대상 청년 목록 시트:
https://drive.google.com/open?id=1z8hzPSlvNM8iyka1YbDpHk6UDASPco8d

해당 시트에서 순배정 제외 대상의 경우 비활성화시키도록 함

**Comment by HWANGJUNYOUNGG** [comment]
2020년 순배정 대상 시트를 보고 시스템에 실제 적용은, 2020년에 맞게 DB 세팅을 하라는 말씀인가요?!1

**Comment by gyummy** [comment]
일단 순서를 따지자면..
1. 2020년도 리더 반영
2. 2020년도 조직 반영 (마을/순)
3. 2020년도 순 배정 반영

**Comment by gyummy** [comment]
2020, 새가족국
한누리(07) - 간사
남효식(05) 
이희원(09)
정의로(09)
박혜경(16)
김예림(16)
박민영(16)

**Comment by gyummy** [comment]
google drive에 2020년 조직안 최종본 및 20또래 정보 추가 완료.

**Comment by HWANGJUNYOUNGG** [comment]
> 2020년도 순배정 대상 청년 목록 시트:
> https://drive.google.com/open?id=1z8hzPSlvNM8iyka1YbDpHk6UDASPco8d
> 
> 해당 시트에서 순배정 제외 대상의 경우 비활성화시키도록 함
-> 순 배정 제외 대상의 경우 순 배정 완료 후 적용하겠습니다:

**Comment by HWANGJUNYOUNGG** [comment]
1, 2, 3청년 순 배정 완료:

배정 못한 청년 목록(2청년)
이민지(08) 순장(DB에는 06으로 되어 있음) - 같은 동일인 인지?
김은지(11)순의 최진석(13) - DB에 비활성화 되어 있음
박영채(11)순의 김상훈(11) - DB에는 13으로 되어 있음
전혁인(12)순의 이현성(13) - DB에 없음(이현섭13은 있음)
고주찬(09)순의 오주환(09) - DB에 비활성화 되어 있음

배정 못한 청년 목록(3청년)
정성권(14)순의 이세원(14) - DB에 없음
김주현(18)순의 김혜지(20), 정은빈(20) - DB 및 고3 명단에 없음
