### ISSUE TITLE
2020년 사용자 등록

### ISSUE THREAD

**Issue by gyummy** [dkeplusi-database/nurture-management-system#78]
2020년도 사용자를 등록한다.

**Comment by gyummy** [comment]
1청년

@ 유진숙팀
유진숙: 기존 계정 사용
김수연: 기존 계정 사용
권병석: kwonbs0126@gmail.com
김유경: saltyk0207@gmail.com
한반석: iron_mental@naver.com

**Comment by gyummy** [comment]
3청년

@ 김세한팀
김세한: 기존 계정 사용
한나은: gksskrma9494@gmail.com
유주연: 기존 계정 사용
정성권: tjdrnjs114@naver.com
조혜린: 기존 계정 사용
정혜진: 기존 계정 사용
강영수:kazers0825@gmail.com

@ 한나팀
한나: 기존 계정 사용
오경현 : dhrudgus@nate.com
김효진 : rkwkd1310@hanmail.net
류경준 : 기존계정 사용
정현아 : 기존계정사용
조혜성 : jhs9787@naver.com
권나연 : wendy778@naver.com

@ 한정호팀
한정호: mn2sjh@gmail.com
김태양: 기존 계정 사용
오혜영: dh2300dud@naver.com
김주현: infenitel@naver.com
고주명: 기존 계정 사용
김윤수: dufwjdzzzz@naver.com
최예지: fshrllll@naver.com

**Comment by HWANGJUNYOUNGG** [comment]
2020년 사용자 등록 완료:
계정 권한 설정 및 비밀번호 초기화 필요

1청년

@ 유진숙팀 UID
유진숙: 기존 계정 사용 6
김수연: 기존 계정 사용 8
권병석: kwonbs0126@gmail.com 83
김유경: saltyk0207@gmail.com 84
한반석: iron_mental@naver.com 85

3청년

@ 김세한팀
김세한: 기존 계정 사용 44
한나은: gksskrma9494@gmail.com 86
유주연: 기존 계정 사용 33
정성권: tjdrnjs114@naver.com 87
조혜린: 기존 계정 사용 39
정혜진: 기존 계정 사용 41
강영수:kazers0825@gmail.com 88

@ 한나팀
한나: 기존 계정 사용 45
오경현 : dhrudgus@nate.com 89
김효진 : rkwkd1310@hanmail.net 90
류경준 : 기존계정 사용 34
정현아 : 기존계정사용 35
조혜성 : jhs9787@naver.com 91
권나연 : wendy778@naver.com 92

@ 한정호팀
한정호: mn2sjh@gmail.com 93
김태양: 기존 계정 사용 31
오혜영: dh2300dud@naver.com 94
김주현: infenitel@naver.com 95
고주명: 기존 계정 사용 29
김윤수: dufwjdzzzz@naver.com 96
최예지: fshrllll@naver.com 97

**Comment by gyummy** [comment]
@HWANGJUNYOUNGG 신규 사용자 초기 비밀번호는 @ 앞까지로 설정합니다.
일단 조직 추가하면 USER_ORG 에 매핑하도록 합시다

**Comment by HWANGJUNYOUNGG** [comment]
기존 사용자를 제외한 새로 추가한 사용자에 한해서 USER_ORG 및 USER_ROLE 테이블에 매핑 설정 및 비밀번호 초기화 완료

**Comment by HWANGJUNYOUNGG** [comment]
2청년 기존, 새로운 사용자 권한 설정 필요(계정 받아야함)

**Comment by gyummy** [comment]
2청년

@최지아팀
최지아: choi.jeeah@gmail.com
한희성: 1030hhs@gmail.com
박영채: dudco222@hanmail.net
김은지: dmswl1724@hanmail.net
전혁인:goorooma5@naver.com


@ 백영은팀
백영은: 기존 계정 사용
인웅진: ingoon88@gmail.com
고주찬: gjc9107@naver.com
신한나: shinna0724@gmail.com
황준영: 기존 계정 사용



@박상민팀
박상민 : 기존계정
이민지 : 기존계정
김혜진 : dksksldk3@naver.com
한상은 : zero7168@naver.com
이지현 : woa413@nate.com
박주성 : tough1202@hanmail.net

**Comment by JJUUUN** [comment]
2청년

@최지아팀
최지아: choi.jeeah@gmail.com 99
한희성: 1030hhs@gmail.com 100
박영채: dudco222@hanmail.net 101
김은지: dmswl1724@hanmail.net 102 
전혁인:goorooma5@naver.com 103

@ 백영은팀
백영은: 기존 계정 사용 16
인웅진: ingoon88@gmail.com 104
고주찬: gjc9107@naver.com 105
신한나: shinna0724@gmail.com 106
황준영: 기존 계정 사용 26

@박상민팀
박상민 : 기존계정 13
이민지 : 기존계정 12
김혜진 : dksksldk3@naver.com 107
한상은 : zero7168@naver.com 108 
이지현 : woa413@nate.com 109
박주성 : tough1202@hanmail.net 110

2청년 USER_ORG 및 USER_ROLE 테이블에 매핑 설정 및 비밀번호 초기화 완료

**Comment by JJUUUN** [comment]
2020년 모든 사용자 등록 완료

**Comment by JJUUUN** [comment]
![image](https://user-images.githubusercontent.com/26572260/71653189-7a50f580-2d6e-11ea-9f30-2113d3315948.png)
중복

**Comment by gyummy** [comment]
> ![image](https://user-images.githubusercontent.com/26572260/71653189-7a50f580-2d6e-11ea-9f30-2113d3315948.png)
> 중복

지우세요 ㅋㅋㅋ

**Comment by gyummy** [comment]
본인이 gmail쓰기를 희망하는것 같으니, naver계정은 비활성화 처리하겠습니다.

**Comment by gyummy** [comment]
> ![image](https://user-images.githubusercontent.com/26572260/71653189-7a50f580-2d6e-11ea-9f30-2113d3315948.png)
> 중복

본인이 gmail쓰기를 희망하는것 같으니, naver계정은 비활성화 처리하겠습니다.

**Comment by gyummy** [comment]
마무리되었으므로 이슈를 닫습니다.

**Comment by JJUUUN** [comment]
USER Table에 2청년 신규 사용자의 계정이 없는 것을 발견했습니다.

**Comment by gyummy** [comment]
> USER Table에 2청년 신규 사용자의 계정이 없는 것을 발견했습니다.

추가했슴다. 앞으로 닫힌 이슈에 코멘트 달 경우에는 열고 달아주세영
