### ISSUE TITLE
사용자 정보 페이지가 나타나지 않는 문제(404)

### ISSUE THREAD

**Issue by JJUUUN** [dkeplusi-database/nurture-management-system#83]
첫 로그인시 '사용자 정보' 페이지에 들어가면 http://youth.dong-kwang.org/user/userInfo 주소인 사용자 정보 페이지가 정상적으로 나오지만, 왼쪽 메뉴바에서 다른 페이지로 이동 후 다시 사용자 정보 메뉴를 클릭하면 Not Found 404 페이지가 나오는 문제가 있습니다.
http://youth.dong-kwang.org/cell/member/information/user/userInfo 이 페이지를 찾을 수 없어서 페이지가 나오지 않는 문제가 있습니다.

**Comment by gyummy** [comment]
@HWANGJUNYOUNGG 이후 담당자는 나로 지정해주길 부탁.

**Comment by gyummy** [comment]
수정 완료
